### ISSUE TITLE
Bug: log processed payload in case of execution error

### ISSUE THREAD

**Issue by martinbaillie** [alexcasalboni/aws-lambda-power-tuning#102]
Hey @alexcasalboni, thanks for the great project. I wrapped a Lambda with it today and it gave some great insight on the ideal configuration.

One small thing that stumped me for a while that I thought I'd mention is that when you make use of a pre-processor function and it goes wrong, the payload reported in the thrown error is the original payload rather than the post-processed payload that was actually sent to the target Lambda: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/lambda/executor.js#L84

Cheers

**Comment by alexcasalboni** [comment]
Thanks @martinbaillie, this is a great catch 💯 

I'll be working on a fix asap.

**Comment by alexcasalboni** [comment]
Fixed in #103, merged, and published on SAR as version `3.3.3` :)
