### ISSUE TITLE
feat: terraform deployment alternative

### ISSUE THREAD

**Issue by nitrocode** [alexcasalboni/aws-lambda-power-tuning#109]
It would be nice to have an alternative to cloud formation so this can be easily deployed to aws using terraform.

**Comment by alexcasalboni** [comment]
Hey @nitrocode, thanks for sharing!

I've been monitoring this issue, which would allow you to use SAR directly: https://github.com/terraform-providers/terraform-provider-aws/issues/3981

In the meantime, it looks like you can use `aws_cloudformation_stack` and deploy [this resource](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/scripts/deploy-sar-app.yml#L6) (`AWS::Serverless::Application`).

I admit I haven't tried this as I don't have a lot of experience with Terraform myself. But it'd be great if we could document an official way to deploy Lambda Power Tuning with Terraform. Using the SAR app looks like a much easier mechanism that doesn't require to maintain two independent templates for SAM/CloudFormation and Terraform.

Do you think you could help me look into this?

**Comment by nitrocode** [comment]
I believe you are referring to something like in this comment.

https://github.com/buildkite/elastic-ci-stack-for-aws/issues/246#issuecomment-399426091

Not my preference but it should be easy enough. Waiting for the day when we can easily convert between the two.

**Comment by alexcasalboni** [comment]
@nitrocode, same here!

Check out this comment too, as referencing a SAR application via `template_body` looks much easier :)

https://github.com/terraform-providers/terraform-provider-aws/issues/3981#issuecomment-680228920

**Comment by Clete2** [comment]
Terraform supports SAR CF stacks natively now.

Try something like this:
```hcl
# Deploys a shared Lambda Power Tuning stack
# https://github.com/alexcasalboni/aws-lambda-power-tuning
resource "aws_serverlessapplicationrepository_cloudformation_stack" "lambda-power-tuning" {
  name           = "my-cool-lambda-power-tuner"
  application_id = "arn:aws:serverlessrepo:us-east-1:451282441545:applications/aws-lambda-power-tuning"
  capabilities   = ["CAPABILITY_IAM"]

  parameters = {
    PowerValues           = "128,192,256,512,1024,2048,3072,4096,5120,6144,7168,8192,9216,10240" # These are defaults, you can override when running the step function
    lambdaResource        = "*"
    totalExecutionTimeout = 900
    visualizationURL      = "https://lambda-power-tuning.show/"
  }
}
```

**Comment by alexcasalboni** [comment]
Thanks for sharing, @Clete2!

I'm going to document this asap :)

It still sounds a bit odd to deploy a CFN stack with Terraform, but I'm sure it will be useful to a lot of folks.

**Comment by Clete2** [comment]
@alexcasalboni  I'm working on a PR to merge documentation for it.

**Comment by Clete2** [comment]
See https://github.com/alexcasalboni/aws-lambda-power-tuning/pull/120
