### ISSUE TITLE
Invocation error with Cannot read property of undefined

### ISSUE THREAD

**Issue by andushow** [alexcasalboni/aws-lambda-power-tuning#112]
Hi guys,

Here's the error (replaced the token with TOKEN), the function is encapsulated in the epsagon handler (don't think it matters).
I am supposed to send a header as "x-auth": "TOKEN"

the execution input is:

```
[  "lambdaARN": "my-lambda-arn",
  "powerValues": [
    128,
    256,
    512,
    1024,
    2048,
    3008
  ],
  "num": 10,
  "payload": {
    "x-auth": "TOKEN"
  },
  "parallelInvocation": true,
  "strategy": "cost"
}]
```

the lambda:
```
import axios, { AxiosRequestConfig } from "axios";
import * as jwt from "jsonwebtoken";
import https from "https";
import { generateLambdaProxyResponse } from "../../helperFunctions/lambdaProxyResponseGenerators";

const httpClient = axios.create({
  httpsAgent: new https.Agent({
    rejectUnauthorized: false,
  }),
});

export const handler = async (event) => {
  let resp = "";
  const token = event.headers["x-auth"];
  const decoded = jwt.decode(token);
  const eventBody = JSON.parse(event.body);

...
```

the error:

```
{
  "error": "Error",
  "cause": {
    "errorType": "Error",
    "errorMessage": "Invocation error (running in parallel): {\"errorType\":\"TypeError\",\"errorMessage\":\"Cannot read property 'x-auth' of undefined\",\"trace\":[\"TypeError: Cannot read property 'x-auth' of undefined\",\"    at t.handler (/var/task/epsagon_handlers/submitDenominationTest-epsagon.js:1:3539)\",\"    at Runtime.handler (/var/task/node_modules/epsagon/dist/bundle.js:1:45447)\",\"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)\"]} with payload \"{\\\"x-auth\\\":\\\"TOKEN\\\"}\"",
    "trace": [
      "Error: Invocation error (running in parallel): {\"errorType\":\"TypeError\",\"errorMessage\":\"Cannot read property 'x-auth' of undefined\",\"trace\":[\"TypeError: Cannot read property 'x-auth' of undefined\",\"    at t.handler (/var/task/epsagon_handlers/submitDenominationTest-epsagon.js:1:3539)\",\"    at Runtime.handler (/var/task/node_modules/epsagon/dist/bundle.js:1:45447)\",\"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)\"]} with payload \"{\\\"x-auth\\\":\\\"TOKEN\\\"}\"",
      "    at /var/task/executor.js:84:19",
      "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
      "    at async Promise.all (index 3)",
      "    at async runInParallel (/var/task/executor.js:89:5)",
      "    at async Runtime.module.exports.handler (/var/task/executor.js:39:19)"
    ]
  }
}
```

Thanks!

**Comment by alexcasalboni** [comment]
Hi @andushow, thanks for reaching out!

I see that your function is reading `event.headers["x-auth"]`, so your payload should look like this:

```json
{
    "headers": {
        "x-auth": "TOKEN"
    }
  }
```

Let me know if this solves your problem :)

**Comment by andushow** [comment]
Making progress,
payload is:
```
{
  "lambdaARN": "my-lambda-arn",
  "powerValues": [
    128
  ],
  "num": 5,
  "payload": {
    "headers": {
      "x-auth": "TOKEN"
    },
    "body": {
      "payload": [
        {
          "denomination": "astana",
          "species_id": "ABELI",
          "analysis_req": "0",
          "user_remark": "my remark",
          "user_id": "129667"
        }
      ]
    }
  },
  "parallelInvocation": true,
  "strategy": "cost"
}
```

error is:

```
{
  "error": "Error",
  "cause": {
    "errorType": "Error",
    "errorMessage": "Invocation error (running in parallel): {\"errorType\":\"SyntaxError\",\"errorMessage\":\"Unexpected token o in JSON at position 1\",\"trace\":[\"SyntaxError: Unexpected token o in JSON at position 1\",\"    at JSON.parse (<anonymous>)\",\"    at t.handler (/var/task/epsagon_handlers/submitDenominationTest-epsagon.js:1:3571)\",\"    at Runtime.handler (/var/task/node_modules/epsagon/dist/bundle.js:1:45447)\",\"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)\"]} with payload \"{\\\"headers\\\":{\\\"x-auth\\\":\\\"TOKEN\\\"},\\\"body\\\":{\\\"payload\\\":[{\\\"denomination\\\":\\\"astana\\\",\\\"species_id\\\":\\\"ABELI\\\",\\\"analysis_req\\\":\\\"0\\\",\\\"user_remark\\\":\\\"my remark\\\",\\\"user_id\\\":\\\"129667\\\"}]}}\"",
    "trace": [
      "Error: Invocation error (running in parallel): {\"errorType\":\"SyntaxError\",\"errorMessage\":\"Unexpected token o in JSON at position 1\",\"trace\":[\"SyntaxError: Unexpected token o in JSON at position 1\",\"    at JSON.parse (<anonymous>)\",\"    at t.handler (/var/task/epsagon_handlers/submitDenominationTest-epsagon.js:1:3571)\",\"    at Runtime.handler (/var/task/node_modules/epsagon/dist/bundle.js:1:45447)\",\"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)\"]} with payload \"{\\\"headers\\\":{\\\"x-auth\\\":\\\"TOKEN\\\"},\\\"body\\\":{\\\"payload\\\":[{\\\"denomination\\\":\\\"astana\\\",\\\"species_id\\\":\\\"ABELI\\\",\\\"analysis_req\\\":\\\"0\\\",\\\"user_remark\\\":\\\"my remark\\\",\\\"user_id\\\":\\\"129667\\\"}]}}\"",
      "    at /var/task/executor.js:84:19",
      "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
      "    at async Promise.all (index 0)",
      "    at async runInParallel (/var/task/executor.js:89:5)",
      "    at async Runtime.module.exports.handler (/var/task/executor.js:39:19)"
    ]
  }
}
```

**Comment by andushow** [comment]
The error could be due to the fact that the Body is already a JavaScript object:
`const eventBody = JSON.parse(event.body);`
and i'm sending as body a JSON:
```
"body": {
      "payload": [
        {
          "denomination": "astana",
          "species_id": "ABELI",
          "analysis_req": "0",
          "user_remark": "my remark",
          "user_id": "129667"
        }
      ]
    }
```
Any thoughts ?

**Comment by andushow** [comment]
fixed it by providing a bse64 encoded body.

**Comment by alexcasalboni** [comment]
Awesome, I'm glad you managed to figure out how to generate the input payload :)

Basically, you need to provide exactly the same payload that API Gateway (or other Lambda triggers) would provide to your Lambda functions.

Let me know how it goes with your tuning results!

**Comment by andushow** [comment]
i run 2 consecutive sets of tests with the same input: 5 times "ALL" RAM size and i got mixed results:

[1. run](https://lambda-power-tuning.show/#gADAAAABQAGAAcABAAJAAoACwAIAA0ADgAPAAwAEQASABMAEAAVABYAFwAUABkAGgAbABgAHQAeAB8AHAAhACIAIwAgACUAJgAnACQAKQAqACsAKAAtAC4ALwAs=;QRcXRMONu0RmRrdEhSuyQ7VhoEPvLphDS/6/Q09bdETyq31EN9AtRBEhTERPWzdEcf2iRPltoUS14bZECheiRFVdo0TaMKxERIyeRO9OqET2aIhEGAOFRN7do0QDHbJEImKjRDdIqUSClqJEHzUYRLWhoEM3cJ9DYKx5Q8kvgUPo9GtDzazHQ6RwoEOPwoRDiai/Q4ylnUPya8lDM7ONQ6SQgUOd9pFDSCFuQ3dXkEMHOmtDUvhzQw==;77PDNc2+pzaArtE2q8kLNs2+Jzbvs0M2EalfNuBCHTdLNUA3tIsGN6e2PDdeuTU3cT2rN8hdqjeArtE39BTBN20q3DesZeg3tifjNxVuADjSbdM3FgrdN/PGEjhU0CM4MgIfONIfJThxPSs4EVuxN4CuUTfJq1g3zb4nN8P8LDe6OjI366B0NzSeezed9EE3YsyENwdLiDcWvK43d+xWN20qXDdkaGE3WqZmN1DkazdHInE3PWB2Nw==)


[2. run](https://lambda-power-tuning.show/#gADAAAABQAGAAcABAAJAAoACwAIAA0ADgAPAAwAEQASABMAEAAVABYAFwAUABkAGgAbABgAHQAeAB8AHAAhACIAIwAgACUAJgAnACQAKQAqACsAKAAtAC4ALwAs=;lpSCRGCcb0QUfmpEavNXRNR2NkSnDUBE9ugLRHG9SkQpfBZEjOXxQ+Ga4kMD/TVEM1P5Q80MLkQwZjJEatM8RDq9NkT5hTRET8sjRBTOBkQpHORDoNPmQ1yPpEOPgmtDImJ6Q+j0X0MK13NDT9tlQ/ILX0PJL2hDXI9kQz3KcUOgk2hDsWReQ3E9YENZMmNDA11rQzNzckNVVWJD2kBZQ532YkNqg2FDyS9QQ+WXV0M3UFhDImJWQw==;PMQZNoCuUTaryYs24EKdNs2+pzbvs8M2zb6nNv2IDTfroPQ2SzXANoCu0TZeuTU366D0NrB4NzcRqV83o6NtNzSeezdizIQ366B0N20qXDdLNUA35vFIN82+JzcQDQM3B0sIN/2IDTfzxhI36gQYN+BCHTfXgCI3zb4nN8P8LDe6OjI3sHg3N6e2PDed9EE3lDJHN4pwTDeArlE3d+xWN20qXDdkaGE3WqZmN1DkazdHInE3PWB2Nw==)
What would you infer from the 2 results ?
Thanks,

**Comment by alexcasalboni** [comment]
Can I ask you which downstream services are you invoking? Maybe you're reading from a (non-serverless) relational database without autoscaling? (or with very slow autoscaling)

Since you have `"parallelInvocation": true` and `"num": 10`, you are invoking your function 460 times concurrently - which might have side effects on your downstream services that can't scale as well as Lambda, resulting in noisy results.

**Comment by andushow** [comment]
The lambdas hit a RDBMS database (Oracle) that has in front ORDS (Oracle REST Data services); from my individual tests, ORDS replies to single requests within 50-200msec ; The parallelism exercise (parallelInvocation) is good, as it mimics how the clients may use the feature (concurrent connections). The database has a queue mechanism in place (Oracle queuing), that's why the response is quite fast for individual requests.

**Comment by alexcasalboni** [comment]
I see, that makes sense!

So I'd try to use `"parallelInvocation": false` to obtain less noisy results and avoid queuing - with the goal of finding the globally optimal power.

Then you can always turn on `"parallelInvocation": true` and even increase `"num": 100` (or more) to run a larger-scale test (almost a stress test). But in this case you can expect noisy results that depends on the downstream service (not on the Lambda performance itself).

**Comment by andushow** [comment]
Thanks Alex!
I get consistent results now, with parallel flag set to false.
[take 1](https://lambda-power-tuning.show/#gADAAAABQAGAAcABAAJAAoACwAIAA0ADgAPAAwAEQASABMAEAAVABYAFwAUABkAGgAbABgAHQAeAB8AHAAhACIAIwAgACUAJgAnACQAKQAqACsAKAAtAC4ALwAs=;CucURMlP3EP2yLtD1AapQ2MJmUOdNotD6DSLQ4mIikNqA31DY0lxQxsockNPu4FDM/N3Q4+ih0PlF3JD6DRkQzMzXENBJ2VDDnRRQzBWUkOdtktDoJNQQ08bUUMUbltDT9tgQ9QGT0NtYFJDOq1PQ8ZSVEPvblJDYKxiQ1I4TUM9ClJDDrRRQ2rDXkNI4VRDAIBKQ8aSTUNVlUtDpPBPQxGRPEPQaTtDzQw7Q+H6MEOgUzRDKRwuQw==;zb6nNYCu0TURqd81q8kLNs2+JzbzxhI2zb4nNqe2PDaArlE2WqZmNjSeezYHS4g288aSNuBCnTbNvqc2ujqyNqe2vDaUMsc2gK7RNm0q3DZapuY2RyLxNjSe+zYQDQM3B0sIN/2IDTfzxhI36gQYN+BCHTfXgCI3zb4nN8P8LDe6OjI3sHg3N6e2PDed9EE3lDJHN4pwTDeArlE3d+xWN/PGEjeYRRY3PMQZN+BCHTeFwSA3KUAkNw==)

[take 2](https://lambda-power-tuning.show/#gADAAAABQAGAAcABAAJAAoACwAIAA0ADgAPAAwAEQASABMAEAAVABYAFwAUABkAGgAbABgAHQAeAB8AHAAhACIAIwAgACUAJgAnACQAKQAqACsAKAAtAC4ALwAs=;ljwTRG1g1UMHOrFDMDafQ/kFlkO4volDZuaDQ6CTeUN3N3RDfvFtQ0jhaUPyi1xDcf1jQ9djX0PvLl1D12NTQ34xWUOMJVVDAMBQQ5NfV0Ps0VBDERFWQxQuVUMAAGRDj0JfQ/lFUkNLfk5DWXJOQ9CpUkNjyVlDYOxOQ4+CU0MKF09DKVxIQ8N1S0Pvbk5DN1BJQ6QwPUPvLkhD8otHQ7y7MEOx5DJDIuI0Qwf6QkOnDTZDhes2Qw==;zb6nNYCu0TURqd81q8kLNs2+JzbzxhI2zb4nNqe2PDaArlE2WqZmNjSeezYHS4g288aSNuBCnTbNvqc2ujqyNqe2vDaUMsc2gK7RNm0q3DZapuY2RyLxNjSe+zYQDQM3B0sIN/2IDTfzxhI36gQYN+BCHTfXgCI3zb4nN8P8LDe6OjI3sHg3N6e2PDed9EE3lDJHNwdLCDeArlE3T0gPN/PGEjeYRRY3PMQZN+BCHTeFwSA3KUAkNw==)

I see that the sweet spot is 1024 MB, do you agree ?

**Comment by alexcasalboni** [comment]
That's where the two curves cross each other, but it's not necessarily the sweet spot.

In this pattern there is no clear winner, it's a tough tradeoff between cost and speed.

I'd go for 448MB, which is consistently faster than 300ms and (only) 75% more expensive than 128MB

1024MB is not that much better than 448MB (20% faster but 2x more expensive).

Since you're pretty close to 200ms between 1024MB and 2024MB, it might be worth refactoring your code a bit, trying to squeeze 10-20ms of performance on average, which would make 1024MB around 33% cheaper (and therefore a more interesting sweet spot).

If you don't care too much about cost and just want to optimize for UX, 2496MB looks quite interesting (35% faster than 448MB and 4x more expensive).

**Comment by andushow** [comment]
Thanks a lot for your insights (and your application), much appreciated!

**Comment by cabouffard** [comment]
> The error could be due to the fact that the Body is already a JavaScript object:
> `const eventBody = JSON.parse(event.body);`
> and i'm sending as body a JSON:
> 
> ```
> "body": {
>       "payload": [
>         {
>           "denomination": "astana",
>           "species_id": "ABELI",
>           "analysis_req": "0",
>           "user_remark": "my remark",
>           "user_id": "129667"
>         }
>       ]
>     }
> ```
> 
> Any thoughts ?

I'm sorry to revive an old thread, but I'm being faced with the same issue. We're `JSON.parse(event.body)` in our function and that's a hard-requirement. I'm unable to make this library work as it seems like if I were to pass an array of JSON as my payload, the Lambda Function receives it as an object and not a string causing the above to fail. We have an array of X items that creates 255KBs of data. If we are to convert to Base64, the string gets bigger than 255KBs and power tuning rejects the input saying it's too large.

I'm not sure what's the best way to resolve this issue. Is there a way to force the body to be interpreted as a string instead of an object?
