### ISSUE TITLE
How can I pass query parameter in the input

### ISSUE THREAD

**Issue by sumanth712bs** [alexcasalboni/aws-lambda-power-tuning#115]
Can someone please let me know how should I pass the query parameters in the payload section of the input?

**Comment by alexcasalboni** [comment]
Hi @sumanth712bs! 

If you mean the Amazon API Gateway integration, your Lambda payload should look like this:

```json
{
  "queryStringParameters": {
    "myparam": "myvalue"
  }
}
```
