### ISSUE TITLE
Request for new chart for aws-lambda-power-tuning. How much RAM to select?

### ISSUE THREAD

**Issue by MeRahulAhire** [alexcasalboni/aws-lambda-power-tuning#119]
As now in 2020 reinvent, AWS as updated the Ram capacity to 10GB so I was curious to know that how much ram should I select? Earlier it was a pretty much convenient to go from 1024-1536MB for optimum performance. If possible could you make a new chart?

**Comment by alexcasalboni** [comment]
Hi @MeRahulAhire! Thanks for asking :) 

Did you deploy Lambda Power Tuning and run it with your function? That's how you will find out the optimal value.

The tool already supports power values up to 10GB, even though the chart in the documentation is not updated.

Keep in mind that the optimal value is not the same for all functions - you'll need to run this tool in your account and find the optimal value for each individual function (or type of function, if you have many functions with similar patterns).

**Comment by MeRahulAhire** [comment]
Sure thanks for correspondence, I'll surely try to use it again

**Comment by MeRahulAhire** [comment]
I'm now trying to run it and had a doubt that do I need to run this repo against my lambda function to check performance or it completely runs separately on its own as a individual. I was getting the error. 
edit:  this page doesn't seem to open https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:451282441545:applications~aws-lambda-power-tuning
