### ISSUE TITLE
Regional latency

### ISSUE THREAD

**Issue by chadbrewbaker** [alexcasalboni/aws-lambda-power-tuning#122]
Some regions are very spread out geographically - which raises the nanosecond/foot speed of light distance penalty with S3/EFS etc. Also regions have different contention against colocated lambdas - certain Fortune 500s spam a single region.

Is there existing functionality for cross region sampling? If not what would be a good API to submit as a PR?

**Comment by chadbrewbaker** [comment]
Incidental but relevant in the IO tuning context - Dynamo/S3/EFS and edge/non-edge. Would require the user to implement specialization for data planes they want to test against and whether data planes have to be pinned to particular regions.  Would also need cross region sampling to simulate inbound traffic. Feed it a geodensity map of your load to sample on.

**Comment by chadbrewbaker** [comment]
And if you are going that far you might as well expand to EC2 Batch arbitrage now that it is per second billing. http://chadbrewbaker.github.io/2020/12/05/inneficent-market.html The market is far from efficient due to Fortune 500s pinning AZs for "security".

**Comment by alexcasalboni** [comment]
Hi @chadbrewbaker, thanks for sharing 🙏 

Just to avoid misunderstandings, could you please clarify how these latency / cross-region concerns would affect the way you optimize the memory/power of individual Lambda functions?

I believe the tool already supports these use cases and constraints, but I can't think of a way to make the optimization strategy aware of these specific use cases.

**Comment by chadbrewbaker** [comment]
Tuning is more than just memory allocation. You also have costs of S3/EFS/DynamoDB/RDS tradeoff and which region runs your lambda the most efficiently.  If you have region external consumers there is also geolocation to take into account.

**Comment by alexcasalboni** [comment]
I see, that makes sense.

Being able to evaluate the cost/performance tradeoff between using S3 vs EFS vs DDB vs RDS for a specific use is indeed important. The same holds for deciding in which region to run a workflow (although this is usually a matter of customer experience / latency for user-facing API's, and data gravity for other kind of workloads).

That said, I feel like these challenges are beyond the scope of Lambda Power Tuning - which is designed to tune Lambda functions, given a use case that you've already (well-)architected.

In other words, once you've chosen a region (usually based on the factors mentioned above) and picked your data layer (usually based on access patterns and other requirements such as durability and volume), Amazon API Gateway and the edge network will take care of optimizing the networking side of things. This is (intentionally) out of the scope of Lambda itself, so you can focus on building applications.

If there is anything specific to Lambda that we can include in the tuning process, I'd love to. For example, we could implement cross-region tuning to invoke the same Lambda function across two different regions and include the corresponding results in the visualization. Although you can already achieving the same by running Lambda Power Tuning twice (just provide the two function ARN's to the same state machine - you don't even need to deploy Lambda Power Tuning to different regions).

**Comment by alexcasalboni** [comment]
Closing for now, as rearchitecting applications is out of scope for Lambda Power Tuning.
