### ISSUE TITLE
Error: RequestTimeout

### ISSUE THREAD

**Issue by ffxsam** [alexcasalboni/aws-lambda-power-tuning#126]
Every time I try to run the state machine, I get this error:
https://sentry.io/share/issue/ee8643881e294f279f963997d85a6ae7/

My Lambda function definitely runs fine when invoked directly, so I'm not sure what this error means or why it's happening.

Any help would be greatly appreciated!

**Comment by alexcasalboni** [comment]
Hi @ffxsam, thanks for sharing this!

A few questions:

1. Are you 100% sure that you're providing the correct input payload? 
2. What memory/power configurations are you testing? Maybe your function requires a minimum amount of RAM to execute properly? (if this is the case, don't test configurations below that value)
3. What is this socket connection about? Is the function trying to connect to an external resource? Does the external resource have a maximum number of connection it can handle? (if so, maybe try to disable parallel execution to reduce the number of connections)

I hope this is useful.

**Comment by ffxsam** [comment]
Thanks @alexcasalboni!

1. For my function, yes. For the power tuner.. maybe? Payload below.
2. See below. And yeah, basically my function is calling ffmpeg to encode audio, so it's a bit intensive. I've left off lower memory configurations that I know would probably time out.
3. No, nothing related to socket connections in my code at all. Just spawning an ffmpeg process and streaming an S3 object into the process and moving files around.

Step Functions payload:
```json
{
  "lambdaARN": "arn:aws:lambda:xx",
  "powerValues": [
    1024,
    2048,
    3008
  ],
  "num": 5,
  "payload": {
    "fileUuid": "c46e8a09-12d0-4545-aa22-c8ce86adb4be",
    "sourceS3Url": "s3://xx/staging/audio/test.wav",
    "destBucket": "xx",
    "destPrefix": "users/xx/audio/fake-uuid/"
  },
  "parallelInvocation": true,
  "strategy": "cost"
}
```

**Comment by alexcasalboni** [comment]
I agree, everything looks ok in the state machine payload.

A few more questions:

1. Do you get the same error with `"parallelInvocation": false`?
2. What memory configuration triggers the error? 1024, 2048, or 3008? (you should be able to see it in the state machine UI)
3. Could you please re-share the stack trae? (your sentry.io link expired)

**Comment by ffxsam** [comment]
Setting `parallelInvocation` to `false` did the trick! Now I have a shiny report to look at. 😁

**Comment by alexcasalboni** [comment]
That's great, @ffxsam!

Any interesting insights? :)

**Comment by ffxsam** [comment]
It confirmed that my decision to go with 2048MB RAM on Lambda functions that use ffmpeg for audio processing was the right one! 😁

**Comment by ffxsam** [comment]
I can leave this issue open, if you want, since the `parallelInvocation: true` option isn't working. And if you need more info from me, let me know.

**Comment by alexcasalboni** [comment]
Could you please share the whole stack trace?

Since you're not invoking/calling any external API or service, it should work great with `parallelInvocation: true` - unless you're hitting your regional limit of concurrent executions. But with `num: 5` and `powerValues: [1024,2048,3008]` you have a total of 15 concurrent executions. You shouldn't be hitting any limit.

I have the feeling this might be a Lambda issue (not related to Lambda Power Tuning), so I'd like to share more info with the service team.

**Comment by ffxsam** [comment]
Sure thing! I'll post some details when I get some spare time.

**Comment by alexcasalboni** [comment]
Hi @ffxsam! I'm closing this issue for now - please feel free to comment here when you can share more details about the issue. I'll be glad to share it directly with the Lambda team to investigate further.
