### ISSUE TITLE
AWS no longer supports nodejs4.3

### ISSUE THREAD

**Issue by this-andy** [alexcasalboni/aws-lambda-power-tuning#13]
Deploying gives this error: An error occurred: CleanerLambdaFunction - The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: aa86828b-4748-11e9-9731-7d5c960221fe)

Changing all references to be nodejs8.10 appears to work

**Comment by alexcasalboni** [comment]
Thanks for reporting, @this-andy 🙏 

I should have done this long ago 😄
