### ISSUE TITLE
I want to deploy power tuning project with npm serverless

### ISSUE THREAD

**Issue by pbmugade** [alexcasalboni/aws-lambda-power-tuning#138]
I am interested to deploy this project with serverless, do I need to manually convert template.yml to serveless.yml?

**Comment by alexcasalboni** [comment]
Hi @pbmugade! Thanks for asking :)

I'd recommend using the SAR application in your serverless.yml template. You can find an example here: https://medium.com/theburningmonk-com/how-to-include-serverless-repository-apps-in-serverless-yml-6d8233c5d684

Here's the SAR resource: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/scripts/deploy-sar-app.yml
