### ISSUE TITLE
Question regarding use with express based lambda deployments

### ISSUE THREAD

**Issue by a-panickar** [alexcasalboni/aws-lambda-power-tuning#146]
Hi,

Thanks for creating this great tool for the community!

I wanted to see if you guys have any recommendations on how to use this tool when it comes to testing express-based Lambda functions where the single deployment has multiple resources and methods?

Simply invoking the lambda function doesn't work in this scenario, is there a way to pass a GET/POST/PUT requests etc., thru the API GW fronting the Lambda instead? 

I understand this is probably not the intended use of the tool, but wanted to check if there are any suggestions/workarounds?

**Comment by alexcasalboni** [comment]
Hi @a-panickar 👋 

You can definitely use the tool to test API Gateway integrations by configuring the `payload` input argument. It's similar to how you configure test events for your Lambda function (for example, for APIGW-less integration tests).

Basically, it means that you don't go through API Gateway at all. Instead, you invoke the Lambda function directly with a payload that includes all the APIGW parameters such as path, method, querystring, body, etc.

And in case you want to power-tune multiple routes or methods, check out [weighted payloads](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/README-INPUT-OUTPUT.md#user-content-weighted-payloads).

**Comment by a-panickar** [comment]
@alexcasalboni 

Thanks for getting back.

Do you have a payload sample I could refer to or any link?

**Comment by alexcasalboni** [comment]
This should be a good starting point: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

You should be able to customize the payload based on what your function is expecting.

**Comment by a-panickar** [comment]
Just adding a reference sample payload in case someone else ends up here looking for the solution.

The below example is for a GET request

```JSON
{
    "lambdaARN": "lambda function ARN",
    "powerValues": [128, 256, 512, 1024, 3008],
    "num": 10,
    "payload": {
        "resource": "",
        "path": "/someapi/v3/someresource/2038618",
        "httpMethod": "GET",
        "headers": {
            "Some-Header": "Header-Value"
        }
    },
    "parallelInvocation": true,
    "strategy": "cost"
}
```
