### ISSUE TITLE
Payload as a simple string

### ISSUE THREAD

**Issue by thomshib** [alexcasalboni/aws-lambda-power-tuning#148]
How to pass string payload for tuner for Lambda function declared as

  public string FunctionHandler(string input, ILambdaContext context)

I tried these
1. "payload": "test data", - It doesn't work. Error lambda invocation
2. "payload" : {} -  It doesn't work. Error lambda invocation
3.  did not pass payload parameter - It doesn't work. Error lambda invocation

Please provide examples of sample payload

**Comment by alexcasalboni** [comment]
Hi @thomshib 👋 

Thanks for reporting this behavior.

The first option (`"payload": "test data"`) should work.

Could you please share what invocation error you're seeing?

**Comment by shibutho-ipipeline** [comment]
Here is the Error details when  "payload": "test data" was used in the invocation

2021-12-07T10:03:06.914Z	034efe87-1d29-4f28-9d95-275e730681b7	ERROR	Invoke Error 	
{
    "errorType": "InvalidRequestContentException",
    "errorMessage": "Could not parse request body into json: Could not parse payload into json: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (byte[])\"test data\"; line: 1, column: 6]",
    "code": "InvalidRequestContentException",
    "message": "Could not parse request body into json: Could not parse payload into json: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (byte[])\"test data\"; line: 1, column: 6]",
    "time": "2021-12-07T10:03:06.913Z",
    "requestId": "66067173-0969-435f-9984-f99a1d41dc32",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 60.4349532985772,
    "stack": [
        "InvalidRequestContentException: Could not parse request body into json: Could not parse payload into json: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')",
        " at [Source: (byte[])\"test data\"; line: 1, column: 6]",
        "    at Object.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}

**Comment by thomshib** [comment]
Here is the error when invoked with "payload": "test data"

2021-12-07T10:03:06.914Z	034efe87-1d29-4f28-9d95-275e730681b7	ERROR	Invoke Error 	
{
    "errorType": "InvalidRequestContentException",
    "errorMessage": "Could not parse request body into json: Could not parse payload into json: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (byte[])\"test data\"; line: 1, column: 6]",
    "code": "InvalidRequestContentException",
    "message": "Could not parse request body into json: Could not parse payload into json: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (byte[])\"test data\"; line: 1, column: 6]",
    "time": "2021-12-07T10:03:06.913Z",
    "requestId": "66067173-0969-435f-9984-f99a1d41dc32",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 60.4349532985772,
    "stack": [
        "InvalidRequestContentException: Could not parse request body into json: Could not parse payload into json: Unrecognized token 'test': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')",
        " at [Source: (byte[])\"test data\"; line: 1, column: 6]",
        "    at Object.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}

**Comment by alexcasalboni** [comment]
Update: I've figured that a correctly encoded string payload should look like this:

```
'"test data"'
```

I've worked on a PR to reproduce the error and propose a bugfix. I should be able to merge this by end of week.

**Comment by alexcasalboni** [comment]
Hi 👋 

I've just merged the bugfix and published version `4.1.3` on SAR. 

Thanks again for reporting this 🙏
