### ISSUE TITLE
Deploying the latest version of lambda power tuning using CDK

### ISSUE THREAD

**Issue by dzkaraka** [alexcasalboni/aws-lambda-power-tuning#156]
Hello! :) 

When following the deployment steps here: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/README-DEPLOY.md#option-3-deploy-the-aws-sar-app-with-aws-cdk, it does not refer to the latest version of the aws lambda power tuning.

It seems like it is referring to 3.4.0 by default:
![Screenshot from 2022-01-21 17-05-59](https://user-images.githubusercontent.com/77258232/150606445-869da816-24a0-4430-a337-921dd13e1ac3.png)

Is there a way to update the semanticVersion to the latest? (except manually updating it) It might help people with debugging things that have been fixed since 3.4.0 :) and miss the semanticVersion step.

**Comment by alexcasalboni** [comment]
Thanks for reporting, @dzkaraka 🙏 

I've created an issue in the cdk-pattern repo, and I've just opened this PR: https://github.com/cdk-patterns/serverless/pull/250

I'll close this issue once the PR is merged.
