### ISSUE TITLE
How can power tuning forward http request to lambda function?

### ISSUE THREAD

**Issue by usabe** [alexcasalboni/aws-lambda-power-tuning#161]
Hi, team,

Our lambda functions are only served through the apiGateway. When I directly send the lambda function test request with ARN to specify the target, it always gives result of "request unhandled". Is there any way I can send URL on top of the ARN for the tuning test? Like adding the URL inside the payload or somewhere so that I can power tune them as other regular lambda functions?

Thanks

**Comment by alexcasalboni** [comment]
Hi @usabe 👋  thanks for reaching out!

I've been thinking about implementing special support to power-tune Lambda functions behind an API Gateway endpoint.

The main challenge is that there are multiple integration types and the event your Lambda function expects is highly dependant on both integration type and any mapping template (Velocity) that your API Gateway is applying. An easy solution (or workaround) would be supporting only the default structure with a simple URL and METHOD mapping.

What `payload` structure are you using right now? Have you looked into the [official payload structure for APIGW documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)?

**Comment by alexcasalboni** [comment]
@usabe yes, you'd need to "manually" construct the full payload (including url, method, headers, etc.).

The fastest solution right now would be printing out the payload structure that your function expects, and then building your power-tuning payload based on that (changing the URL/METHOD based on your tuning needs).

Simply use the JSON input as your `payload` input for the power-tuning state machine.

**Comment by usabe** [comment]
Great. Then I'll try that. Thank you, Alex. Your help is really appreciated.

**Comment by alexcasalboni** [comment]
Closing this for now. Please reopen if you need more help :)
