### ISSUE TITLE
Initializer Failure: ResourceConflictException

### ISSUE THREAD

**Issue by LimaGuilherme** [alexcasalboni/aws-lambda-power-tuning#175]
I'm trying to run my lambda in a state machine and get this error.
```
`{\"errorType\":\"ResourceConflictException\",\"errorMessage\":\"The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-west-2` ...

 operation cannot be performed at this time. An update is in progress for resource
```

I already try a several numbers of different functions.

The lambda state in question 

```
"State": "Active",
"LastUpdateStatus": "Successful",
```

**Comment by alexcasalboni** [comment]
Hi @LimaGuilherme  👋  thanks for reporting 🙏 

What version of Lambda Power Tuning are you using? Please make sure it's the latest.

**Comment by LimaGuilherme** [comment]
@alexcasalboni Hello,
I'm deployed a new version of a state machine using the version 4.2.1 and works like charm.

**Comment by alexcasalboni** [comment]
Thanks for sharing, @LimaGuilherme 😄 

Let me know if you get stuck somewhere. Happy to help.
