### ISSUE TITLE
Need to support Lambda version

### ISSUE THREAD

**Issue by ah3185** [alexcasalboni/aws-lambda-power-tuning#185]
if ARN for versioned Lambda is specified, the tool will fail, at least with Step Function console

**Comment by alexcasalboni** [comment]
Here's a screen recording of the initial bug report:

https://user-images.githubusercontent.com/2457588/216347981-e779f25e-22bf-4df0-9817-1ea9355b591c.mov

I could not reproduce this error and it seems like a (transient) Lambda bug that isn't happening anymore.

Please do re-open this in case it happens again.
