### ISSUE TITLE
Lambda layer usage

### ISSUE THREAD

**Issue by macdrorepo** [alexcasalboni/aws-lambda-power-tuning#187]
Hello,

Is there a way to plug a custom lambda layer (which is acutally used by by lambda in "prod") to testing purposues with this tool?
For now step functions are failing with error that lambda can't import missing libs from layer.

**Comment by alexcasalboni** [comment]
Hi @macdrorepo, thanks for asking :)

Yes, you should be able to run any Lambda function, with or without Layers.

Before running the Step Functions state machine, please make sure that your function runs properly (no syntax error, no missing libraries, no missing downstream dependencies, no other kind of bugs, etc.). Lambda Power Tuning assumes that your function can run successfully when invoked with the given payload. 

If you see a "can't import missing libs from layer" error, it should have nothing to do with Lambda Power Tuning. So I'd recommend debugging your function code and configuration before power-tuning it. Are you 100% sure the same layer is already used in prod with the same function code and the same runtime?
