### ISSUE TITLE
lumigo-cli no longer maintained

### ISSUE THREAD

**Issue by gliptak** [alexcasalboni/aws-lambda-power-tuning#193]
https://github.com/lumigo-io/lumigo-CLI

will it stay a deployment option?

**Comment by alexcasalboni** [comment]
Very good point!

I'll remove "Option 4" from here: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/README-DEPLOY.md

And maybe just leave a quick reference with a "deprecated" warning:


> If you don't want to deal with any Infrastructure as Code tool, you can use one of the following:
>1. The [Lumigo CLI](https://www.npmjs.com/package/lumigo-cli#lumigo-cli-powertune-lambda) (WARNING: deprecated)
>2. The [Lambda Power Tuner UI](#option5) 

Thank you for flagging this, @gliptak!

**Comment by alexcasalboni** [comment]
Done 👌
