### ISSUE TITLE
adding an option to get all the configurations results

### ISSUE THREAD

**Issue by oriel351** [alexcasalboni/aws-lambda-power-tuning#207]
Hey,

Currently, when executing the step function, the output would be the duration and cost of the best configuration.
What about adding additional parameter to the input json, so that in the output there will be an array of objects, each corresponds to different memory configuration execution, and let the user handle the data and use it as input to another process.
Thanks!

**Comment by oriel351** [comment]
@alexcasalboni  yes that sounds good! it  would definitely do the work.
Thanks :)

**Comment by alexcasalboni** [comment]
@oriel351 do you have any experience with AWS Step Functions and Node.js? Would you feel comfortable taking a first stab at this? There's no wrong answer, of course :) If not, I'll be happy to jump on this later this month.

**Comment by oriel351** [comment]
@alexcasalboni  yeah why not :) , I'll could get to it towards the weekend,

**Comment by alexcasalboni** [comment]
@oriel351 did you manage to find some time to work on this? :)

**Comment by alexcasalboni** [comment]
This was implemented in #231 and merged 👌  

I'm closing this issue :)
