### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by austin-poulter-torus** [alexcasalboni/aws-lambda-power-tuning#221]
AWS is starting to send out emails reminding people to update their Node 16 Lambdas. Just a friendly reminder that this should be done in the next few months before the support ends.

I'm happy to submit a PR if that will be helpful. I'm just not sure what Terraform testing needs to be done since I use the SAR version.

**Comment by alexcasalboni** [comment]
Hi @austin-poulter-torus 👋  thanks for reaching out!

I'd definitely appreciate a PR here 👌 

Switching to `nodejs20.x` shouldn't be too much of a pain for both CloudFormation and Terraform.

There isn't a Terraform-specific test suite, but the runtime values are consistent between CloudFormation and APIs, so we should just use `nodejs20.x` everywhere.
