### ISSUE TITLE
Getting Error While Increasing Power values to 10240 MB

### ISSUE THREAD

**Issue by ajayprasaddev** [alexcasalboni/aws-lambda-power-tuning#224]
Below is the input to pass step function to execute 

{
  "lambdaARN": "arn:aws:lambda:ap-south-1:157551582236:function:MyFunc",
  "powerValues": [
    128,
    256,
    512,
    1024,
    2048,
    3008,
    4032,
    4096,
    4160,
    4224,
    4288,
    4352,
    4416,
    4480,
    4544,
    4608,
    4672,
    4736,
    4800,
    4864,
    4928,
    4992,
    5056,
    5120,
    5184,
    5248,
    5312,
    5376,
    5440,
    5504,
    5568,
    5632,
    5696,
    5760,
    5824,
    5888,
    5952,
    6016,
    6080,
    6144,
    6208,
    6272,
    6336,
    6400,
    6464,
    6528,
    6592,
    6656,
    6720,
    6784,
    6848,
    6912,
    6976,
    7040,
    7104,
    7168,
    7232,
    7296,
    7360,
    7424,
    7488,
    7552,
    7616,
    7680,
    7744,
    7808,
    7872,
    7936,
    8000,
    8064,
    8128,
    8192,
    8256,
    8320,
    8384,
    8448,
    8512,
    8576,
    8640,
    8704,
    8768,
    8832,
    8896,
    8960,
    9024,
    9088,
    9152,
    9216,
    9280,
    9344,
    9408,
    9472,
    9536,
    9600,
    9664,
    9728,
    9792,
    9856,
    9920,
    9984,
    10048,
    10112,
    10176,
    10240
  ],
  "num": 50,
  "payload": {},
  "parallelInvocation": true,
  "strategy": "cost"
}

Getting below error 
{
  "error": "ValidationException",
  "cause": {
    "errorType": "ValidationException",
    "errorMessage": "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008",
    "trace": [
      "ValidationException: 'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008",
      "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)",
      "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)",
      "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
      "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
      "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
      "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
      "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
      "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
      "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
      "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)"
    ]
  }
}

Kindly help on this
Thanks

**Comment by alexcasalboni** [comment]
Hi @ajayprasaddev 👋  thanks for reaching out!

Please see [this post to learn more about the error](https://repost.aws/questions/QUKruWYNDYTSmP17jCnIz6IQ/questions/QUKruWYNDYTSmP17jCnIz6IQ/unable-to-set-lambda-memory-over-3008mb?) (you'll need to contact support and raise that soft limit).

I'm closing the issue since it's not related to Lambda Power Tuning. Please feel free to add more comments or open a new issue if you still encounter issues afterwards :)
