### ISSUE TITLE
Power Tuning Result not showing 'Execution Time'

### ISSUE THREAD

**Issue by keshavyadav** [alexcasalboni/aws-lambda-power-tuning#251]
I ran the power tuning on my handler and see that the result indicates `invocation time` and not `execution time`
https://lambda-power-tuning.show/#gAAAAQACAAQACA==;mpn1QXd3X0EAAIBARESkQAAAoEA=;Gs2LM0mLfDOXTxAzY3fYM31jNDQ=

How do we get the same analysis for Execution Time ?

**Comment by alexcasalboni** [comment]
Hi @keshavyadav, thanks for reaching out 🙏 

Practically, "invocation" and "execution" are treated as synonyms there. Just to make sure we're on the same page, what would be the difference between "invocation time" and "execution time"?

**Comment by keshavyadav** [comment]
Thanks for confirming that they are the same. `Invocation Time` by literal meaning seems like time taken to invoke the function. Given that all the examples on had 'Execution Time' mentioned, I was confused.

**Comment by alexcasalboni** [comment]
Closing for now, we're investigating internally.
