### ISSUE TITLE
Function not found: arn:aws:lambda:eu-central-RAM128

### ISSUE THREAD

**Issue by poonkothai-p** [alexcasalboni/aws-lambda-power-tuning#254]
Hi
I was trying to check the optimal memory for one lambda using this tool. however lambda execution failed with this error Function not found: arn:aws:lambda:region:functoin:RAM128 or  Function not found: arn:aws:lambda:region:functoin:RAM256 etc. Is there any prerequisites to be done for this
Required permissions are there for step function

We are trying with python based lambda

Thanks
Poongkothai

**Comment by alexcasalboni** [comment]
Hi,

Thanks for reaching out!

I’d suggest double-checking the ARN of your function as it seems to contain
a typo (“functoin” instead of “function”).

Could you please share the Step Function input as well?

**Comment by poonkothai-p** [comment]
Thanks
