### ISSUE TITLE
Change visualizationURL after installation

### ISSUE THREAD

**Issue by paul-uz** [alexcasalboni/aws-lambda-power-tuning#255]
How can I change the `visualizationURL` after I have installed the Power Tuner on my account with the default value? I;'ve like to change it to something else but cannot find the option anywhere

**Comment by alexcasalboni** [comment]
Hi 👋 thanks for reaching out!

The visualization URL can only be configured at deploy time, as it becomes
an environment variable for the Lambda function and it needs to be
available at creation time.

I’d suggest to deploy a new stack of Lambda Power Tuning with the new URL.

Alternatively, you could also just replace the default host name with your
custom URL before visiting it. All the relevant
parameters/numbers/statistics are passed via hash.

I hope this helps. And I’d be glad to hear more about what you’re doing
with your custom visualization. That repository hasn’t been updated in a
while and I wouldn’t hate building a new version with more viz features.

**Comment by paul-uz** [comment]
Can't I just change the env variable in the Lambda?

**Comment by alexcasalboni** [comment]
That would work too, if you prefer a quick workaround :)

**Comment by paul-uz** [comment]
I guess the main issue is there is no quick way to get to view the Viz data. You have to view the output JSON and highlight the link and copy n paste it. Would be great if there was a way to pipe this through to a system automatically

**Comment by alexcasalboni** [comment]
Thanks for sharing, @paul-uz! I understand what you mean. 

That's one of the downsides of using Step Functions, in the sense that it doesn't come with a built-in visualization mechanism.

Some folks are automating this by running the entire power-tuning process in an automated way, then grabbing the JSON output and doing all sort of things (storing results in a database, visualizing in table format for internal reports, taking a screenshot of the visualization page, etc). 

The starting point could be as sample as this sample bash script: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/scripts/execute.sh

**Comment by alexcasalboni** [comment]
Closing for now.
