### ISSUE TITLE
Workflow fails at `Branching` step after 15 minutes

### ISSUE THREAD

**Issue by garysassano** [alexcasalboni/aws-lambda-power-tuning#267]
![image](https://github.com/user-attachments/assets/7b1a4fad-fd96-48f3-9042-5b16d46781b7)

![image](https://github.com/user-attachments/assets/e5002d1d-1267-42e4-acf2-3874dc518365)

**Comment by KathleenLamarre** [comment]
> ![image](https://github.com/user-attachments/assets/7b1a4fad-fd96-48f3-9042-5b16d46781b7)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/e5002d1d-1267-42e4-acf2-3874dc518365)
> 
>

**Comment by garysassano** [comment]
I invocated the state machine a second time with half the `num` and it worked.

Here are the two executions:

![image](https://github.com/user-attachments/assets/e0b393aa-8790-45fe-ab53-7774a51c365f)


The input passed to the state machine the first time:

```json
{
  "lambdaARN": "XXX",
  "powerValues": [
    512,
    1024,
    1536,
    2048,
    3008
  ],
  "num": 20,
  "payload": {},
  "strategy": "cost"
}
```

The input passed to the state machine the second time:

```json
{
  "lambdaARN": "XXX",
  "powerValues": [
    512,
    1024,
    1536,
    2048,
    3008
  ],
  "num": 10,
  "payload": {},
  "strategy": "cost"
}
```

It's odd that it still hadn't finished after 15 minutes if you consider that it took less than 5 minutes with half the `num`.

**Comment by alexcasalboni** [comment]
Hi, thanks for reaching out!

That looks odd indeed. It sounds like one of the invocations got stuck (and
then everything failed at the global 15min timeout).

I’d suggest debugging the individual steps and execution logs, so you can
double-check which invocation took so long.

If the problem persists with num: 20, I would also consider using
parallelInvocation: true to speed everything up considerably, if you can
afford running *all* the functions concurrently (without downstream issues).

**Comment by garysassano** [comment]
There were actually several successful executions before that error:

![image](https://github.com/user-attachments/assets/a86f7a15-105b-4682-b47b-ad2d77131b88)

I tried with the `parallelInvocation` originally, and this was the result:

![image](https://github.com/user-attachments/assets/78b44da1-f51e-41cc-963d-52fd011c15c4)

I'm unsure why that's the case considering I'm running everything in an empty test account, so I should have 1000 concurrent executions available for Lambda.

**Comment by alexcasalboni** [comment]
> There were actually several successful executions before that error:

Can you click on `MapIterationFailed` and `TaskStateAborted` to dive into what happened?



> I'm unsure why that's the case considering I'm running everything in an empty test account, so I should have 1000 concurrent executions available for Lambda.

Regarding the maximum concurrency, check out this article: https://benellis.cloud/my-lambda-concurrency-applied-quota-is-only-10-but-why

Sometimes new account have a max concurrency of 10 (instead of 1000). You should be able to verify it here: [console.aws.amazon.com/servicequotas/home/services/lambda/quotas/L-B99A9384](https://console.aws.amazon.com/servicequotas/home/services/lambda/quotas/L-B99A9384)

**Comment by garysassano** [comment]
> Can you click on MapIterationFailed and TaskStateAborted to dive into what happened?

They are the ones I attached in OP. Totally unhelpful.

![image](https://github.com/user-attachments/assets/7b1a4fad-fd96-48f3-9042-5b16d46781b7)


> Sometimes new account have a max concurrency of 10 (instead of 1000). You should be able to verify it here: [console.aws.amazon.com/servicequotas/home/services/lambda/quotas/L-B99A9384](https://console.aws.amazon.com/servicequotas/home/services/lambda/quotas/L-B99A9384)

You are right! Didn't know this was a thing.

![image](https://github.com/user-attachments/assets/e80ea844-ebbe-4b05-be36-edf874a83d49)

**Comment by alexcasalboni** [comment]
I would go and check the Executor function logs, there might be some hints at what failed exactly.

Is it always the branch with index 0 that fails? Is it just an invoke timeout? Does your function actually get invoked?

**Comment by garysassano** [comment]
> I would go and check the Executor function logs, there might be some hints at what failed exactly.

These are the Executor function logs at the exact time when the state machine failed.

![cw-logs](https://github.com/user-attachments/assets/0d7af336-684d-4d69-beca-c8aaf238b7a7)

**Comment by garysassano** [comment]
> I would go and check the Executor function logs, there might be some hints at what failed exactly.

These are the Executor function logs at the exact time when the state machine failed.

![cw-logs](https://github.com/user-attachments/assets/0d7af336-684d-4d69-beca-c8aaf238b7a7)

I checked also the `cron-function` execution that was triggered by the Executor and there were no errors.

Really a mystery why the `Branching` step failed; I wasn't able to reproduce the issue in any way with the successive state machine runs.

**Comment by alexcasalboni** [comment]
Sorry to hear this.

It sounds like it was a transient error of the Lambda API (very unlikely to happen as I’ve never seen this before). It could be related to the low concurrency limit too, but that sounds odd as I’d expect a throttling error instead.

Let us know if the problem shows up again (closing this issue for now).
