### ISSUE TITLE
Provide results for all power levels

### ISSUE THREAD

**Issue by aswathrao** [alexcasalboni/aws-lambda-power-tuning#30]
Soetimes it is preferable to opt for a power level that takes shorter execution time rather than one that minimizes the cost. (https://www.jeremydaly.com/15-key-takeaways-from-the-serverless-talk-at-aws-startup-day/). Accordingly it will be nice if the tool produces a CSV file containing for each power level, the corresponding execution time and the cost.

**Comment by alexcasalboni** [comment]
Thanks for your input, @aswathrao.

If you look at the Executor steps' output, you'll find the statistics for all configurations.

Also, check out this comment in the code: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/lambda/finalizer.js#L18

Basically, I'm planning to add more tuning strategies to find the optimal configuration. Right now the default and only strategy is cost. Speed is definitely another very good one.

And this could be implemented as a state machine input:

```json
{
  "num": 10,
  "lambdaARN": "blabla",
  "strategy": "cost|speed"
}
```

I hope this makes sense. I will soon open a new issue to implement new optimization strategies. In the meantime, you can find all the power level's speed and cost in the executors' output.

**Comment by aswathrao** [comment]
Thanks for your quick response and for being patient with a "paper engineer". Due to my limited technical knowledge, I didn't know of the Executor steps' output. Will pass it along.

In case you didn't catch on, I am a big advocate of this tool within my org, my comment(s) are made in my zeal to make sure it is used within my organization.
