### ISSUE TITLE
Multiple optimization strategies

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#31]
As mentioned in #30, new optimization strategies could be more useful in specific use cases.

The default strategy could remain `cost`, but a few more can be implemented.

The second most straightforward strategy is `speed`, and we should implement it in a way that's easy for new contributors to add implement strategies.

The `Finalizer` function takes all the statistics as input and will return the optimal configuration, so everything can be implemented there.

**Comment by pavelloz** [comment]
I know its closed, but looking at the readme im just wondering, how hard would it be do also add "balanced" (to not say optimal).

Having weights on cost and speed, we could assume that balanced means most of the performance, for half the cost. Or where performance hit the point of diminishing return and does not provide bg speedup, but cost more.

I would even say that those weights could be configurable, apart from having sensible defaults.

Im using lambda extensively and to be honest i dont see any case where i want to go all cost, or all performance. I could achieve this with 5 minutes of clicking on my own. Having data of 30-100 runs/power breakpoint should give me definietly more information than what i would guess with high probability of being correct.

**Comment by alexcasalboni** [comment]
Thanks @pavelloz, I've opened #38 to keep track of this new idea :)
