### ISSUE TITLE
Set of test payloads

### ISSUE THREAD

**Issue by pavelloz** [alexcasalboni/aws-lambda-power-tuning#37]
Lets take the hello world of lambda world for example: compress image from s3 using sharp.

Having a function that does complicated thing which depends so heavily on the input, forces us to test it using multiple different variants, ie:

* big file
* small file
* format 1, format 2, format 3
* extremely big file
* transformations passed as options

It would be nice if Power Tuning could take multiple events as an inputs, and before recommending power, take into consideration output from all the different tests.

Ideally, I could tell the percentage of tests run by any given test (ie. medium file with jpeg format - 50%, extremely big file - 3%, transformations - 5%) - so that extremely big file would not skew the results too much (average likes to do that).

**Comment by alexcasalboni** [comment]
Great idea, @pavelloz!

Which input structure would you suggest?

Would you provide a list of payloads? (same percentage) 

```JSON
{"payload": ["payload1", "payload2", ...]}
```

Or a weighted object?

```JSON
{"payload": {
    "payload1": 0.6,
    "payload2": 0.4,
}}
```

Or maybe a more complex structure to be more forward-compatible?

```JSON
{"payloads": {
    "payload-name-1": {"payload": ".....", "percentage": 0.6},
    "payload-name-2": {"payload": ".....", "percentage": 0.4},
}}
```

**Comment by pavelloz** [comment]
I would personally probably split it into multiple files that are based on original AWS event - which would be similar to how serverless framework does it (`serverless invoke -e myEvent.json`). 

Having 3 json files for 3 different occasions:

* test/big_file.json
* test/small_file.json
* test/extremely_big_file.json

Each would have full event that is compatible with AWS events. This would make it much easier to just copy them over, just in case people have them saved in their aws console / serverless projects for testing. I know i have a bunch of them - even though most of the times very little is changed, i always base them on AWS-provided templates.

Example s3 event: https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html 

I dont know if thats only my OCD, but separating test events from actual config might also be beneficial for maintaining lambda code, serverless config (or any other framework that uses events) and power tuning in one repo, just waiting to be run after a big change in code has been made. In my eyes it would add a lot of confidence, using the same events for manual testing, automated testing and power tuning. 

Now, to the actual power tuning api, i think having the event sources in place, that could be achieved in a small hash manner:

```json
{
  "events": [
    { "name": "small", "path": "test/small_file.json", "weight": 0.7 },
    { "name": "big", "path": "test/big_file.json", "weight": 0.5 },
    { "name": "extremely_big", "path": "test/extremely_big_file.json", "weight": 0.1 }
  ]
}
```

**Comment by alexcasalboni** [comment]
Ideally, I'd want this project to be fully functional when you deploy it from the AWS Serverless Application Repository (SAR). That's why I was thinking of providing events as the state machine input, without any local file required.

**Comment by pavelloz** [comment]
Then back to your idea (i have no idea about SAR apps constrains).

The only thing to account for is variety of event types.
They are finite and i assume 90% of use cases can be covered by those events: SNS, SQS, S3, API Gateway, DynamoDB.

**Comment by alexcasalboni** [comment]
I'm thinking that maybe we should just document how to integrate AWS SAM Local ([generate command](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-generate-event.html)) with the execution of this state machine ([execute script](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/execute.sh)).

You'd only need to replace the third line with this:

```bash
INPUT=$(sam local generate-event s3 put --bucket <bucket> --key <key>)
```

Even though it'd require you to execute it somewhere locally, we wouldn't reinvent the wheel for events generation.

For this issue, let's focus on supporting multiple weighted payloads as the state machine input. The actual event generation can be solved based on how you decide to execute the state machine.

The structure you proposed makes sense, with these edits:

```json
{
  "payload": [
    { "name": "small", "payload": "{...}", "weight": 0.7 },
    { "name": "big", "payload": "{...}", "weight": 0.2 },
    { "name": "extremely_big", "payload": "{...}", "weight": 0.1 }
  ]
}
```

A few differences wrt your proposal:
- we need to inline the payload
-  I'd like to use the `payload` parameter for backward compatibility
- I think it'd be easier if weights always sum up to 1 (so you can consider them as percentages)

**Comment by pavelloz** [comment]
Yep :)

If those are percentages, i would write them as Ints, as you noticed, it is to consider them as percentages, and this is user facing api. ;)

I wonder though, if it should be percentages, or just treated as ratio.
If i set up `small: 10, big: 2, extremely_big: 1` then i know small will happen 10x more often than extremely, and big will happen 2x more often than extremely. Then i can add another event that will base off of that.

With percentages, i adding new event will require rewriting all the events.

**Comment by alexcasalboni** [comment]
That's a fair point. Makes sense :)

Should we have any limitation about the max number of payloads allowed? Or enforce a minimum value of `num` to ensure that results are statistically relevant? At the moment we have `num >= 5`. Maybe we can change it to `num >= 5 * count(payloads)`?

**Comment by pavelloz** [comment]
Yes, probably, because there is no point (statistically) in running test low number of times, (ie once) but i wouldnt set it high either, because people wanting to see **if** it works (from tech POV - if they have set up their credentials correctly, etc. - _preflight_ so to speak) or not, will try to run as small sample as possible, just to see if it didnt error along the way - at least thats what i do on my first run :)

BTW. Maybe thats an (good?) idea for a feature, `dry-run` - that would connect to AWS, check if everything CAN be done when the time comes.

It is probably better to educate on margin or error (or however its called in statistics - standard variation? level of confidence?) to give user tools to make the best decision in given use case without being inaccessible.
Multiple payloads increases complexity so it may need a sentence, or two, and a hyperlink in the readme :)

**Comment by alexcasalboni** [comment]
Well you can always execute the state machine with `num=1` to verify if everything works fine, so I wouldn't introduce a special `dry-run` option for now.

Regarding statistical awareness, I'm going to add a feature that allows you to visualize numbers in a chart such as [this one](https://github.com/alexcasalboni/aws-lambda-power-tuning-ui/raw/master/sample-screenshot.png).

**Comment by pavelloz** [comment]
> num=1

I thought min was 5 ;)

**Comment by alexcasalboni** [comment]
Good point :) well unless your function runs for 5 minutes, even num=5
means an almost-free execution cost.

idk, let’s consider this. Could you open an other issue for dry-run so we
can discuss it further and collect some other opinions there?

**Comment by alexcasalboni** [comment]
Ok, back to the new functionality we were discussing: multiple payloads as execution input.

Let's confirm this input format:

```json
{
  "payload": [
    { "name": "small", "payload": "{...}", "weight": 10 },
    { "name": "big", "payload": "{...}", "weight": 30 },
    { "name": "extremely_big", "payload": "{...}", "weight": 60 }
  ]
}
```

in which weight are relative to each other. In this case, it'd be 60% for "extremely_big", 30% for "big", and 10% for "small".

Regarding the implementation, we currently support two payload formats: string and object. This functionality will make it accept lists as well. See current implementation here: https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/lambda/executor.js#L58

Do you feel like taking a first stab at this? :)

I'd recommend converting the `payload` parameter into a `payloadFunc` callable that will transparently randomize which payload gets used based on the computed percentage.

So that we can simply do this everywhere:

```js
await runInParallel(num, lambdaARN, lambdaAlias, payloadFunc());
```

**Comment by pavelloz** [comment]
1) I would personally not use 60, 30, 10 - if that is supposed to be a ratio, 6, 3, 1 should be simpler and would not suggest summing up to anything.

I think you are further down the implementation path in your brain than me, thats why you are converting it to percentages - im at the beginning - more in the API design phase so that it makes the most sense for someone typing in those numbers.

This is still how i imagine it being the simplest for the average user: https://github.com/alexcasalboni/aws-lambda-power-tuning/issues/37#issuecomment-536977853

2) Im more of a frontend guy that wrote couple lambdas (one using serverless framework) to optimize performance of our companys stack. I have 0 experience with SAR, SAM and their constrains - you would need to rewrite everything i try, probably. Just by looking at your tests, by my estimation, im nowhere near to be able to contribute your level of code :)

**Comment by alexcasalboni** [comment]
Yeah, 60-30-10 was just an example. 6-3-1 would work too. Or even 600-300-100. Or even 300-150-50. As long as the relative proportion holds :)

No worries about the implementation, I'll give this a shot in the next few weeks myself.

**Comment by alexcasalboni** [comment]
Implemented in #54!

I'll update the doc and publish on SAR asap.

**Comment by Sojer23** [comment]
Hi @alexcasalboni , thanks for this amazing tool 😄  I am using it to some test in my final master project.

I have a question in relation with weighted payloads, can weights be equals to get similar number of execution for each payload?

For example:
```
"payload": [
{ "payload": {...}, "weight": 10},
{ "payload": {...}, "weight": 10},
{ "payload": {...}, "weight": 10},
{ "payload": {...}, "weight": 10},
{ "payload": {...}, "weight": 10}
]
```
How do you consider this way of testing? If you don't know the main weight of your endpoint...only a big range

**Comment by alexcasalboni** [comment]
@Sojer23 yes, that's correct! You can use any weight (`10`, `20` or `999`) and it will used as a relative weight wrt the total weight :) So if you use `10` for your 5 payloads, they'll be used 20% of the time (exactly 20%!).
