### ISSUE TITLE
Weighted optimization strategy

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#38]
Based on @pavelloz's feedback in #31, we could have a configurable weight between `speed` and `cost`.

Since there are many different use cases and very subjective ways to optimize for cost vs. speed, such a weight would need to be very well documented, imho.

In the long-term, we might be able to "categorize" a given function into some sort of optimization class based on the speed-cost relation across memory configurations, and come up with a globally optimal strategy for each class.

FYI @matteo-ronchetti is already working on the first iteration of this :)

**Comment by alexcasalboni** [comment]
@matteo-ronchetti can you share your progress so far?

**Comment by matteo-ronchetti** [comment]
Current idea is to choose the configuration by weighting together both time and cost. For each lambda size i let t_i and c_i be the corresponding time and cost normalized such that their biggest value is 1. Let alpha be a parameter between 0 and 1 that specifies the trade-off between cost and time. Alpha = 0 means we only care about the time, Alpha = 1 only about the cost. Then the optimal size may be found by computing the minimum:  
![8c1389f7-ce55-48f1-a512-cf916df929dc](https://user-images.githubusercontent.com/4364535/66201823-7c8ab180-e6a4-11e9-9706-c97e55a8a27e.jpeg)
I've tried this formulation on two use cases one CPU heavy and one that highly depends on the latency of an external service.
This is the cost/time plot for the network bound lambda:
![lambda_time_cost_1](https://user-images.githubusercontent.com/4364535/66201982-fb7fea00-e6a4-11e9-9f8a-7011b4facce7.png)
Min cost configuration is 128Mb, min time is 1536Mb (which is expensive), the above formula with lambda between 0.2 and 0.8 gives as result 256Mb which to me seems the most reasonable.
This is the cost/time plot for the CPU bound lambda:
![lambda_time_cost_2](https://user-images.githubusercontent.com/4364535/66202205-6f21f700-e6a5-11e9-9a9d-2a198d1bf407.png)
Here min cost is 1536Mb, min time is 3008Mb, all values of lambda (not to close to 1) give as result  1536Mb

**Comment by matteo-ronchetti** [comment]
What would be a good syntax for specifying the balanced strategy? I'm thinking about something like:
```json
{
    "strategy": "balanced",
    "strategyAlpha": 0.5
}
```
strategyAlpha would get a default of 0.5 and be used only when strategy is "balanced"
