### ISSUE TITLE
Default nodejs version runtime

### ISSUE THREAD

**Issue by pavelloz** [alexcasalboni/aws-lambda-power-tuning#39]
Looking at https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

I wonder if https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/template.yml#L27 should be 10.x by default.

I know there are differences between AMI and AMI2, and even in my case i could not migrate one lambda that uses `aws-chrome-lambda` because of incompatibilities.

But there is a case to be made for either setting it to a current AWS recommended version, or writing one sentence on it in documentation as a heads up. :)

Or maybe i dont understand how it works yet, im not the best in reading SAM/CF manifests.

**Comment by alexcasalboni** [comment]
The runtime used in this project doesn't impact the runtime you are using for your own Lambda functions.

So my suggestion is to not worry about it too much. I'll take care of upgrading the Node.js runtime when needed. I think at this point it's mature enough to upgrade, but again this shouldn't be a concern for your own functions (which could be developed in Python, Go, .NET, or any other runtime).

**Comment by pavelloz** [comment]
Yeah, thats why i anticipated writing last sentence :)
