### ISSUE TITLE
Can we use the tool for stress testing?

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#56]
If you test only one power configuration and use a very large `num`, this tool could be used for stress testing Lambda functions and visualize average cost and execution time.

We could design a different visualization to be used when testing only one power configuration, where we could visualize more detailed statistics.

**Comment by alexcasalboni** [comment]
@matteo-ronchetti can you think of a different type of visualization for this use case? Maybe to highlight percentile numbers? (e.g. cost and performance at p50, p90, p99, etc.)

**Comment by reni11111** [comment]
i would love this feature, stress testing has been a pain in lambda

**Comment by alexcasalboni** [comment]
@reni11111 thanks 🎉 

Could you briefly share what pain points you've encountered and what you'd expect?

For example, would you expect to perform both power-tuning and stress-testing in a single run? My assumption was that you'd run stress-testing with only one power configuration.

**Comment by reni11111** [comment]
Yes, u just read my mind, all in a single run would be a great feature for my projects (some UI would be even better for presentations).
BTW very good interview at serverless chat

**Comment by alexcasalboni** [comment]
Closing this, as it's out of scope. While it is possible to use the tool for invoking a function `num` times, stress-testing and power-tuning are supposed to be independent processes, performed by ad-hoc tools. In particular, I'd recommend power-tuning first in order to identify the best tradeoff between performance and cost. Then you can use ad-hoc tools such as [Artillery](https://www.artillery.io) to perform stress testing and collect detailed statistics about the overall performance (not just Lambda function invocation time).
