### ISSUE TITLE
When cost are the same, should return higher performing power

### ISSUE THREAD

**Issue by theburningmonk** [alexcasalboni/aws-lambda-power-tuning#60]
Here's an example where raising power improves the performance and kept the cost the same:
![image](https://user-images.githubusercontent.com/546969/72305186-4d0c1d80-3673-11ea-942e-6aa789f0cd89.png)

But in this, the power tuning tool still returned 128MB but logically it should have returned 256MB.

**Comment by alexcasalboni** [comment]
Thanks @theburningmonk!

I'll review this later this week, add a couple of tests and make sure the most performing option is recommended when cost is the same.

**Comment by theburningmonk** [comment]
thanks 👍

**Comment by alexcasalboni** [comment]
This should be fixed now :)

I haven't re-published to SAR yet, though.
