### ISSUE TITLE
Optimise multible functions at once

### ISSUE THREAD

**Issue by simonfrey** [alexcasalboni/aws-lambda-power-tuning#61]
As stated in #55 it would be nice to be able to optimize multiple chained functions at once. @alexcasalboni stated that he thinks the optimum for the overall chain would in his opinion correlating with the optimum of all indiviual functions.

I researched a bit and there is research (a bachelor thesis I sadly can't share) that the pareto optimum for all functions differs indeed from just the edge optimization of the single functions individually. 

It would be nice to be able to optimize a chain of functions or even a step function state machine with this tool.

**Comment by alexcasalboni** [comment]
Thanks @simonfrey!

Any chance you can share some numeric results or an extract from this bachelor thesis? I understand the absolute optimal may differ from the single-functions optimal, but if it's a matter of +/- 1% on average, it might not be worth building a general purpose N-functions optimizer.

In my personal intuition, these two optimal values are very close to each other and many other developers in the industry may not be that interested in the theorieical optimum unless it differs a lot.

Let's also keep in mind the additional cost of optimizing itself - which is very low in the single-function case but might growth non-linearly with the number of functions to optimize.

**Comment by alexcasalboni** [comment]
@simonfrey any updates on this? :)

**Comment by simonfrey** [comment]
Not so far. I am looked deeper into the research and it sees you are right. It is not that propable that multiple optimisation will be a lot better than individual one
