### ISSUE TITLE
Provide a context to Lambda function when running the lambda power tuning

### ISSUE THREAD

**Issue by NoraBo** [alexcasalboni/aws-lambda-power-tuning#66]
The lambda function that is being tuned requires a context. 

How can we pass the context to this lambda function when running the tuning step function using the following:
{
    "lambdaARN": "lambda ARN",
    "powerValues": [128, 256],
    "num": 5,
    "payload": {},
    "parallelInvocation": true,
    "strategy": "balanced"
}

**Comment by alexcasalboni** [comment]
Hi @NoraBo,

What kind of context exactly?

The input `payload` isn't enough?

Or do you mean the actual [Lambda Context Object](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html)?

**Comment by NoraBo** [comment]
Hi Alex,

Thanks for getting back to me.

This lambda is invoked from the AWS API gateway. The context I am referring to would be the HTTP context.  I think I found a way on how to do that by setting the payload to:

"payload": {
    "headers": "",
    "requestContext": "",
    "pathParameters": ""
  }

**Comment by alexcasalboni** [comment]
Yes, that’s correct :) well done!

**Comment by alexcasalboni** [comment]
Closing this.
