### ISSUE TITLE
Feature Request - Leverage X-Ray to analyze different segments

### ISSUE THREAD

**Issue by Graham42** [alexcasalboni/aws-lambda-power-tuning#68]
I have a lambda that makes an external network call as part of it's execution which is a variable I can't control. It would be awesome if this tool leveraged [AWS X-Ray](https://aws.amazon.com/xray/) to be able to report on the effect of memory tuning on various segments of execution.

![image](https://user-images.githubusercontent.com/2476733/74448325-c3ee2f00-4e48-11ea-9fd2-750f60539c11.png)

Questions this approach could answer: 
- How do different memory allocations affect my initialization segement? This is a primary factor in cold start times
- How do different memory allocations affect TLS connection setup times? I've heard that it can be significant, would be helpful want to quantify

**Comment by alexcasalboni** [comment]
Hi @Graham42, thanks for sharing!

I can see how this would add more performance insights to help you understand what to optimize and in which cases.

As far as overall performance tuning is concerned, the tool assumes you want to optimize the largest majority of warm executions by excluding performance outliers from its analysis (the top and bottom 20% is excluded - [see code here](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/lambda/utils.js#L226)).

So at the moment cold starts aren't really a focus - also considering the recent release of [Provisioned Concurrency for Lambda](https://aws.amazon.com/blogs/aws/new-provisioned-concurrency-for-lambda-functions/).

On the other hand, TLS connection setup times might actually affect warm invocations as well - in those scenarios involving 3rd-party API's where you cannot reuse connections at all.

Let me figure out if there's a straightforward way to integrate X-Ray data.

In the meantime, you can still run Lambda Power Tuning while X-Ray profiling is enabled. Then you can inspect X-Ray yourself and filter on memory to visualize the corresponding traces as follows:

```
resource.arn = "YOUR_ARN:RAM1024"
```

Also a screenshot of the X-Ray console filtered by alias:

![aws-xray](https://user-images.githubusercontent.com/2457588/74452072-dbe1a500-4e80-11ea-826f-3d298e10b1fe.jpg)

**Comment by alexcasalboni** [comment]
Closing for now.
