### ISSUE TITLE
InvalidParameterValueException on v3.2.3 

### ISSUE THREAD

**Issue by theburningmonk** [alexcasalboni/aws-lambda-power-tuning#69]
Just deployed the latest v3.2.3 and every time I run the new state machine I get the following error:

```
"error": {
    "Error": "InvalidParameterValueException",
    "Cause": "{\"errorType\":\"InvalidParameterValueException\",\"errorMessage\":\"The role defined for the function cannot be assumed by Lambda.\",\"trace\":[\"InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.\",\"    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)\",\"    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)\",\"    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\",\"    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\",\"    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\",\"    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\",\"    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\",\"    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\",\"    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\",\"    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)\"]}"
  }
}
```

**Comment by alexcasalboni** [comment]
Hi @theburningmonk, I'm sorry to hear this.

I've just deployed v3.2.3 on a new stack (via SAR) and it's working fine.

>  The role defined for the function cannot be assumed by Lambda.

This sounds like something went wrong with the IAM role, but there is nothing related to IAM in the last release and I can't reproduce the error with a brand new deployment.

1. Can you double-check the IAM roles?
2. Can you share more details about how to reproduce this behaviour step by step?
3. Do you see anything more interesting/useful in the Step Functions web console?

**Comment by theburningmonk** [comment]
mm.. so I tested against another function and it worked, so it might be an issue with the function itself under test. But strangely, I ran a test against the same function with v3.2.2 and it worked, so it feels like something changed and I'm not quite sure what

**Comment by alexcasalboni** [comment]
The only thing that changed in v3.2.3 is the new `dryRun` option, which shouldn't impact IAM in any way.

I'll keep this issue open - let me know if you find out more and/or if you find a way to reproduce it.

**Comment by alexcasalboni** [comment]
@theburningmonk any update on this? did you fix it?

**Comment by theburningmonk** [comment]
@alexcasalboni it hasn't shown up again, I wonder if the error was coming from the function itself. Let me close this.
