### ISSUE TITLE
Payload does not support GET Methods

### ISSUE THREAD

**Issue by sseshachala** [alexcasalboni/aws-lambda-power-tuning#72]
I am trying to test with lambda functions that expects Query parameters. I am passing the params via payload, but throws invocation errors with null object references. 
Our functions expects Query parameters. Any chance we can support query params to be passed with payload?

**Comment by alexcasalboni** [comment]
Hi @sseshachala, 

Can you share with me what payload are you passing now and what input you need for your Lambda function?

If you are trying to simulate the input event of an Amazon API Gateway request, you should be able to add querystring parameters in your payload as follows:

```json
{
  "method": "GET",
  "body" : "body-value",
  "headers": {
    "my-header": "header-value"
  },
  "queryParams": {
    "my-param": "param-value"
  }
}
```

**Comment by sseshachala** [comment]
Thank you that worked
