### ISSUE TITLE
Use the correct regional base price

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#77]
The base price for Lambda executions (128MB, 100ms) is `$0.0000002083` in almost every region.

Here are the regions where the price is slightly different:
- Hong Kong (ap-east-1): `$0.0000002865` (+37%)
- Cape Town (af-south-1): `$0.0000002763` (+32%)
- Bahrain (me-south-1): `$0.0000002583` (+24%)

This difference should be considered in two places:
- in the state machine output `results.stateMachine.lambdaCost`
- in the visualization (charts)

We should update the utilities `utils. computePrice(...)` and `utils. computeTotalCost(...)`, used by the Executor function [here](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/lambda/executor.js#L137).

Thanks #75 for bringing this up.

**Comment by gino247** [comment]
I have put in a pull request to address this, I hope.
Also added basic sinon for now, for util stubbing.
Introduced a new Environment variable to replace **minCost**.
New variable is a query like string, i.e **region=price,default=`$0.000000208`**
Basically changed the calling of `utils.computePrice(...)` and `utils.computeTotalCost(...)`.

Regards,
Eugene

**Comment by alexcasalboni** [comment]
Thanks @gino247 this is awesome! I'm going to review the PR and share some feedback asap!
