### ISSUE TITLE
Regional base price selection (Step Functions)

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#80]
Similarly to #77, we should use the correct regional price of Step Functions based on where the state machine is executed (which might be different from the input function's region!).

Each state transition costs `$0.000025` in almost every region, with some exceptions:
- default: $0.025
- eu-south-1: $0.02625
- us-west-1: $0.0279
- af-south-1: $0.02975
- ap-east-1: $0.0275
- ap-south-1: $0.0285
- ap-northeast-2: $0.0271
- eu-south-1: $0.02625
- eu-west-3: $0.0297
- me-south-1: $0.0275
- sa-east-1: $0.0375
- us-gov-east-1: $0.03
- us-gov-west-1: $0.03

The state machine execution cost is computed [here](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/lambda/utils.js#L9):

```javascript
module.exports.stepFunctionsCost = (nPower) => +(0.000025 * (6 + nPower)).toFixed(5);
```

The formula to compute the # of state transitions is: `6 + COUNT(POWERVALUES)`, therefore the Step Functions cost will be `REGIONAL_COST * NUMBER_OF_TRANSITIONS`.

**Comment by alexcasalboni** [comment]
Note: because there are many more "exceptions" wrt Lambda's pricing, maybe we could think of storing this information in its own JSON file (rather than an env variable). I'm not a big fan of this because it'd add a few lines of code to every function instead of a single env variable in template.yml. But let's consider it :)

**Comment by alexcasalboni** [comment]
FYI I've put together a simple script to fetch regional prices via API in case we'll need to automate this process in the future: https://gist.github.com/alexcasalboni/b9b6c23b659f86591ac53bcc80c486cf

**Comment by gino247** [comment]
Hi,

Looking into this.
How will we know in which region this step function is running?
Can we rely on the predefined environment variables available, i.e. AWS_REGION?

Regards,
Eugene

**Comment by alexcasalboni** [comment]
Yes, `AWS_REGION` should work great.

From the [documentation](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime): "The AWS Region where the Lambda function is executed."

For clarify: its value might be different from the region where the input Lambda function is running, but that's ok. Lambda Power Tuning works with functions in any region, but you still need to deploy the state machine in a region :)

**Comment by gino247** [comment]
Cool.
Then for now let's stick to the ENV approach.
Maybe we can run some sort of `aws cli` or `node getCostMapping` command and use the output with `sed` to replace the value in `template.yml` when you deploy the application?
This could happen in the `deploy.sh`.
Not pretty but will rely on the user to have a few things in place on deploy.

Your thoughts?

Regards,
Eugene
