### ISSUE TITLE
Question not an issue: In output, i see cost as 8.32e-7. Is that the cost for that execution we need to pay?

### ISSUE THREAD

**Issue by ChandrewR** [alexcasalboni/aws-lambda-power-tuning#83]
In output, i see cost as 8.32e-7. Is that the cost for that execution we need to pay?

```json
{
  "power": 512,
  "cost": 8.32e-7,
  "duration": 47.3920138888889,
  "stateMachine": {
    "executionCost": 0.0003,
    "lambdaCost": 0.003546192,
    "visualization": "https://lambda-power-tuning.show/#<Embeded code>"
  }
}
```

**Comment by ChandrewR** [comment]
I see the cost as below in the documentation page. I didnt get the cost in output it shows. Can you pls clarify what it means exactly..

AWS Step Functions cost: it corresponds to the number of state transitions during the state machine execution; this cost depends on the number of tested power values, and it's approximately 0.000025 * (6 + N) where N is the number of power values; for example, if you test the 6 default power values, the state machine cost will be $0.0003
AWS Lambda cost related to your function's executions: it depends on three factors: 1) number of invocations that you configure as input (num), the number of tested power configurations (powerValues), and the average invocation time of your function; for example, if you test all the default power configurations with num: 100 and all invocations take less than 100ms, the Lambda cost will be approximately $0.001
AWS Lambda cost related to Initializer, Executor, Cleaner, and Analyzer: for most cases it's negligible, especially if you enable parallelInvocation: true; this cost is not included in the results.stateMachine output to keep the state machine simple and easy to read and debug

**Comment by alexcasalboni** [comment]
Hi @ChandrewR, thanks for using the tool :)

Let me clarify the meaning of that JSON output, field by field:

* **power**: the optimal power/memory value
* **cost**: the average cost corresponding to the optimal power
* **duration**: the average execution time corresponding to the optimal power

And then you have the `stateMachine` field, which represents metadata about this specific state machine execution:

* **executionCost**: the Step Functions cost of this tuning execution
* **lambdaCost**: the Lambda cost of this tuning execution (it includes only your Lambda function's execution)
* **visualization**: the URL to visualize results


I hope it is clearer now. Let me know if you need any specific clarification :)

**Comment by ChandrewR** [comment]
cost: the average cost corresponding to the optimal power - Is this per lambda invocation?

**Comment by alexcasalboni** [comment]
Yes, correct. It's the average cost of each invocation using that power.

**Comment by ChandrewR** [comment]
Got it Alex.Thank you

**Comment by alexcasalboni** [comment]
Any time :)
