### ISSUE TITLE
Environment variable minRAM must contain string

### ISSUE THREAD

**Issue by teebu** [alexcasalboni/aws-lambda-power-tuning#9]
July 4, 2018
https://github.com/serverless/serverless/issues/5094#issue-338302359
After updating today to 1.28.0, Serverless (or a dependency) now expects all environment variables to be strings. This sounds reasonable, but it's a breaking change so I'm making people aware.

```
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  Environment variable minRAM must contain string

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.11.1
     Serverless Version:     1.28.0
```

Manually changing the serverless.base.yml file, to strings, fixes that issue.

```
    minRAM: '128'
    minCost: '0.000000208'
```

**Comment by alexcasalboni** [comment]
Thanks for reporting, @teebu!

I guess that up to that version the string conversion was appening automatically (by the framework or by CloudFormation).

I can think of two ways to fix asap.

1. Force this repo to use an older version of the framework (in case we expect the breaking chance to be reverted at some point). This should be enough:

```yaml
frameworkVersion: ">=1.0.0 <1.28.0"
```

2. Update `serverless.base.yml` as you did.


I'd rather go for option 2. Could you please open a PR and submit your changes for review?

**Comment by alexcasalboni** [comment]
Closing, as this was fixed in https://github.com/alexcasalboni/aws-lambda-power-tuning/commit/0d26257de0cd117227baa54382c3ba702e6f50dd 💯
